;; -*-no-byte-compile: t; -*-

;; verilog stuff

(defun vendetta-init-zero-verilog-style()
  (setq verilog-align-ifelse t)
  (setq verilog-indent-tabs-mode nil)
  (setq verilog-tab-always-indent t)
  (setq verilog-indent-level 4)
  (setq verilog-indent-level-module 4)
  (setq verilog-indent-level-declaration 4)
  (setq verilog-indent-level-behavioral 4)
  (setq verilog-indent-level-directive 0)
  (setq verilog-cexp-indent 4)
  (setq verilog-case-indent 4)
  (setq verilog-indent-begin-after-if 0)
  (setq verilog-indent-declaration-macros nil)
  (setq verilog-indent-lists t)
  (setq verilog-auto-newline t)
  (setq verilog-auto-indent-on-newline t)
  (setq verilog-indent-begin-after-if nil)
  (setq verilog-auto-delete-trailing-whitespace t)
  (setq verilog-auto-read-includes t)
  (setq verilog-auto-template-warn-unused t)
  (setq verilog-auto-undef t)
  (setq verilog-auto-unused t)
  (setq verilog-auto-lineup '(all))
  (setq verilog-auto-endcomments t)
  (setq verilog-tab-to-comment nil)
  (setq verilog-date-scientific-format t)
  (setq verilog-minimum-comment-distance 8)
  (setq verilog-highlight-grouping-keywords t)
  (setq verilog-highlight-modules t)
  (setq verilog-highlight-includes t)
  (setq verilog-highlight-p1800-keywords t))

(defun vendetta-verilog-mode-hook()
  (vendetta-init-zero-verilog-style)
  (font-lock-fontify-buffer))

;;(add-to-list 'auto-mode-alist '("\\.[ds]?va?h?\\'" . verilog-mode))
(add-to-list 'auto-mode-alist "\\.v$\\'" 'verilog-mode)
(add-to-list 'auto-mode-alist "\\.vh$\\'" 'verilog-mode)
(add-to-list 'auto-mode-alist "\\.dv$\\'" 'verilog-mode)
(add-to-list 'auto-mode-alist "testfixture.verilog" 'verilog-mode)
(add-to-list 'auto-mode-alist "testfixture.template" 'verilog-mode)
