;; verilog stuff

(defalias 'font-lock-ensure 'font-lock-fontify-buffer)

(defun vendetta-init-velho-verilog-style()
  (custom-set-variables
   '(verilog-align-ifelse t)
   '(verilog-indent-tabs-mode nil)
   '(verilog-tab-always-indent t)
   '(verilog-indent-level 4)
   '(verilog-indent-level-module 4)
   '(verilog-indent-level-declaration 4)
   '(verilog-indent-level-behavioral 4)
   '(verilog-indent-level-directive 0)
   '(verilog-cexp-indent 4)
   '(verilog-case-indent 4)
   '(verilog-indent-begin-after-if 0)
   '(verilog-indent-declaration-macros nil)
   '(verilog-indent-lists t)
   '(verilog-auto-newline t)
   '(verilog-auto-indent-on-newline t)
   '(verilog-indent-begin-after-if nil)
   '(verilog-auto-delete-trailing-whitespace t)
   '(verilog-auto-read-includes t)
   '(verilog-auto-template-warn-unused t)
   '(verilog-auto-undef t)
   '(verilog-auto-unused t)
   '(verilog-auto-lineup '(all))
   '(verilog-auto-endcomments t)
   '(verilog-tab-to-comment nil)
   '(verilog-date-scientific-format t)
   '(verilog-minimum-comment-distance 8)
   '(verilog-highlight-grouping-keywords nil)
   '(verilog-highlight-modules nil)
   '(verilog-highlight-includes nil)
   '(verilog-highlight-p1800-keywords nil)))
;;   '(verilog-tool 'verilog-linter)
;;   '(verilog-linter "verilator -Wall --lint-only")
;;   '(verilog-coverage "verilator --coverage")
;;   '(verilog-simulator "verilator")
;;   '(verilog-compiler "verilator --sc"))

(defun vendetta-init-velho-verilog-font-lock-style()
  (font-lock-add-keywords 'verilog-mode
                          '(("\\(module\\)" . font-lock-block-face) 
                            ("\\(endmodule\\)" . font-lock-block-face)
                            ("\\(function\\)" . font-lock-block-face)
                            ("\\(endfunction\\)" . font-lock-block-face)
                            ("\\(config\\)" . font-lock-config-face)
                            ("\\(cell\\)" . font-lock-block-face)
                            ("\\(initial\\)" . font-lock-preprocessor-face)
                            ("\\(assign\\)" . font-lock-function-face)
                            ("\\(deassign\\)" . font-lock-function-face)
                            ("\\(posedge\\)" . font-lock-block-face)
                            ("\\(negedge\\)" . font-lock-block-face)
                            ("\\(edge\\)" . font-lock-block-face)
                            ("\\(begin\\)" . font-lock-block-face)
                            ("\\(if\\)" . font-lock-block-face)
                            ("\\(else\\)" . font-lock-block-face)
                            ("\\(do\\)" . font-lock-block-face)
                            ("\\(begin\\)" . font-lock-block-face)
                            ("\\(end\\)" . font-lock-block-face)
                            ("\\(mem\\)" . font-lock-mamory-face)
                            ("\\(always\\)" . font-lock-block-face)
                            ("\\(case\\)" . font-lock-block-face)
                            ("\\(casex\\)" . font-lock-block-face)
                            ("\\(casez\\)" . font-lock-block-face)
                            ("\\(default\\)" . font-lock-keyword-face)
                            ("\\(endcase\\)" . font-lock-block-face)
                            ("\\(wire\\)" . font-lock-wire-face)
                            ("\\(automatic\\)" . font-lock-memory-face)
                            ("\\(input\\)" . font-lock-memory-face)
                            ("\\(output\\)" . font-lock-memory-face)
                            ("\\(reg\\)" . font-lock-register-face)
                            ("\\(cell\\)" . font-lock-preprocessor-face)
                            ("\\(config\\)" . font-lock-preprocessor-face)
                            ("\\(endconfig\\)" . font-lock-preprocessor-face)
                            ("\\(defparam\\)" . font-lock-macro-face)
                            ("\\(design\\)" . font-lock-register-face)
                            ("\\(disable\\)" . font-lock-warning-face)
                            ("\\(reg\\)" . font-lock-register-face)
                            ("\\(V0*\\)" . font-lock-function-face)
                            ("\\(generate\\)" . font-lock-preprocessor-face)
                            ("\\(endgenerate\\)" . font-lock-preprocessor-face)
                            ("\\(primitive\\)" . font-lock-block-face)
                            ("\\(endprimitive\\)" . font-lock-block-face)
                            ("\\(specify\\)" . font-lock-debug-face)
                            ("\\(endspecify\\)" . font-lock-debug-face)
                            ("\\(table\\)" . font-lock-macro-face)
                            ("\\(endtable\\)" . font-lock-macro-face)
                            ("\\(specify\\)" . font-lock-document-face)
                            ("\\(endspecify\\)" . font-lock-document-face)
                            ("\\(task\\)" . font-lock-thread-face)
                            ("\\(endtask\\)" . font-lock-thread-face)
                            ("\\b\\w'`'\\b" . font-lock-preprocessor-face))))

(defun vendetta-verilog-mode-hook()
  (vendetta-init-velho-verilog-style)
;;  (vendetta-init-velho-verilog-font-lock-style)
;;  (defalias 'font-lock-ensure 'font-lock-fontify-buffer)
  (add-hook 'local-write-file-hooks
            (lambda() (untabify (point-min) (point-max)))))
